branch-defaults:
  master:
    environment: we-alone-env
global:
  application_name: we-alone
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.09 v2.0.6 running PHP 5.6
  default_region: ap-southeast-2
  profile: eb-cli
  sc: git
